language: python
python: 2.7
install: pip install -r requirements.txt && pip install .
script:
  - dcs-logwatcher --help
  - wget https://s3.amazonaws.com/dsc-misc/sample.log.gz && gunzip sample.log.gz
  - py.test
